version: '3.8'

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "100m"
   max-file: "1"

services:
 php:
   build: .
   volumes:
     - ./www:/var/www
   depends_on:
     - nginx
   restart: unless-stopped
   networks:
     - net
   logging: *logging
   healthcheck:
     test: curl --fail http://nginx | grep "works" || exit 1
     interval: 1s
     timeout: 3s
     retries: 5

 nginx:
   image: "nginx:alpine"
   ports:
     - 80:80
   volumes:
     - ./www:/var/www
     - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
   restart: unless-stopped
   networks:
     - net
   logging: *logging

networks:
 net:
